return {
  -- Statement-oriented chunks only.
  ["expression_statement"] = true,
  ["assignment"] = true,
  ["augmented_assignment"] = true,
  ["return_statement"] = true,
  ["import_statement"] = true,
  ["import_from_statement"] = true,
  ["for_statement"] = true,
  ["while_statement"] = true,
  ["if_statement"] = true,
  ["function_definition"] = true,
  ["class_definition"] = true,
  ["try_statement"] = true,
  ["with_statement"] = true,
  ["raise_statement"] = true,
  ["assert_statement"] = true,
  ["delete_statement"] = true,
  ["global_statement"] = true,
  ["nonlocal_statement"] = true,
  ["match_statement"] = true,
  ["type_alias_statement"] = true,
  ["pass_statement"] = true,
  ["break_statement"] = true,
  ["continue_statement"] = true,
}
